apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aimstack
  name: aimstack
  namespace: aimstack
spec:
  selector:
    matchLabels:
      app: aimstack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aimstack
    spec:
      containers:
        - name: server
          image: aimstack:0.0.1
          args: ["aim server --repo $(AIM_REPO) --host 0.0.0.0 --port 53800 --workers $(AIM_WORKERS)"]
          ports:
            - containerPort: 53800
              protocol: TCP
              name: server
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: aimstack
          volumeMounts:
            - mountPath: /aimstack
              name: aim-runs
        - name: ui
          image: aimstack:0.0.1
          args: ["aim up --host 0.0.0.0 --port 43800 --workers $(AIM_WORKERS) --repo $(AIM_REPO)"]
          ports:
            - containerPort: 43800
              protocol: TCP
              name: ui
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: aimstack
          volumeMounts:
            - mountPath: /aimstack
              name: aim-runs
      volumes:
        - name: aim-runs
          hostPath:
            path: /data
