apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/geekbass/aimstack?ref=v0.0.1
- pvc.yaml
- pv.yaml
# Patch in the EFS PVC
patchesStrategicMerge:
- init-job.yaml
- deployment.yaml
images:
  - name: aimstack
    newName: wbassler/aimstack
    newTag: "v0.0.1"
