apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-aimstack
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: YOUR_NFS_SERVER_ADDRESS_HERE
    path: "/aimstack"
