kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-aimstack
  namespace: aimstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
